[build]
  command = "python3 app.py"  # Replace with your Flask app's main Python script

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  "/*" = [
    "Cache-Control: public, max-age=0, must-revalidate"
  ]

[functions]
  directory = "netlify/functions"  # Replace with the directory containing your serverless functions (if any)
